[project]
name = "fused-ce-loss"
version = "0.0.1"

[build-system]
requires = [
    "scikit-build-core>=0.3.3", 
    "pybind11"
]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
wheel.install-dir = "fused_ce_loss"
